### ISSUE TITLE
Suggest this to be added inside the Godot engine for everyone to use

### ISSUE THREAD

**Issue by twaritwaikar** [awkwardpolygons/viewport-spy#1]
Based on the discussion on the developer chatroom on Rocket.Chat on this addon, it seems some devs find that this addon might be worthwhile to add to the base editor.

If you want you can open a proposal by creating an issue here: https://github.com/godotengine/godot-proposals/

It doesn't guarantee that the addon actually gets added into the engine but at least the other developers will get to see that this kind of enhancement is indeed helpful :D

**Comment by Xrayez** [comment]
The amount of code used to implement this feature makes me think that this *should* be part of the engine. 🙂

**Comment by arccoza** [comment]
Thanks folks, I've opened a [proposal](https://github.com/godotengine/godot-proposals/issues/2471).
